### ISSUE TITLE
compiliert nicht: class PrivateArea fehlt

### ISSUE THREAD

**Issue by SprachRolf** [PaulStahr/SimpleBoardGameSimulator#10]
Die Klasse PrivateArea wird bei mir nicht gefunden -- ist die vielleicht noch nicht eingecheckt?

**Comment by PaulStahr** [comment]
Also im aktuellen Master und auch im dev ist die drin (/src/gui/PrivateArea.java). Laut travis haben die beiden Branches auch compiliert. Ist es möglich, dass die irgendwie beim Merge verloren gegangen ist?

**Comment by SprachRolf** [comment]
Es geht wieder.
