### ISSUE TITLE
Test First

### ISSUE THREAD

**Issue by SprachRolf** [PaulStahr/SimpleBoardGameSimulator#11]
Habt ihr schon Vorstellungen davon, welches Framework wir für Unit-Tests verwenden sollen?

Falls nicht, übernehme ich gerne die Auswahl und Einrichtung.

**Comment by PaulStahr** [comment]
Meines wissens bisher nicht, ich hab bisher nur JUnitTest verwendet, und keinen wirklichen Überblick was es sonst noch so gibt. Am besten schreibst du dann einmal vorher noch worauf deine Auswahl gefallen ist. Ich wäre da aber relativ offen.

**Comment by PaulStahr** [comment]
JUnitTest4 ist installiert, vorhandene Tests im package test werden automatisch auf travis ausgeführt
