### ISSUE TITLE
Meilenstein 2:

### ISSUE THREAD

**Issue by SprachRolf** [PaulStahr/SimpleBoardGameSimulator#14]
SimpleBoardGame ist für Spieler benutzbar, die den Umgang mit Computern gewohnt sind.
-- Man kann damit die folgenden Kartenspiele spielen:
Skat, Schafkopfen, Rummecub, Schwarzer Peter, Leg-das-Rohr (Diese Liste steht zur Diskussion!)
-- Man kann nicht spielen:
Schach, Go, Spiele mit nicht-rechteckigen Karten, Spiele mit ungleich großen Karten, Mensch-ärger dich nicht (weil man dazu ein Spielbrett hochladen muss, ich schlage vor, das wird Meilenstein 3 oder so)... bitte erweitern oder ändern!
In Meilenstein 2 kann man 
- bis zu 8 Spieler an den Tisch setzen
- bis zu 4 Wu:rfel auf dem Tisch haben
- ein Set gleichformatiger, rechteckiger Karten bequem als Bilddateien ins Spiel laden
- Spieler, die ihre Internetverbindung verlieren bekommen ihre Karten wieder, wenn sie sich mit gleichem Spielernamen wieder einloggen.

Was meint ihr, welche Features in Meilenstein 2 geho;ren und welche nicht?

**Comment by PaulStahr** [comment]
Ich denke, dass wir die Spieleranzahl, sowie objektanzahl erstmal unbegrenzt lassen sollten. Der vierte Punkt sollte eigentlich schon erfüllt sein, habe es aber noch nicht getestet.
