### ISSUE TITLE
Spielstand: neuer Spieler angemeldet

### ISSUE THREAD

**Issue by SprachRolf** [PaulStahr/SimpleBoardGameSimulator#19]
Der Chat wird noch nicht aktualisiert, wenn sich ein neuer Spieler am Spiel anmeldet.
Das bedeutet, der erste angemeldete Spieler kann nur Nachrichten an alle schicken.
Ein Spieler kann einem später eingeloggten Spieler keine Privatnachrichten schicken.

**Comment by PaulStahr** [comment]
Eigentlich sollte das seit folgendem Commit behoben sein:
https://github.com/PaulStahr/SimpleBoardGameSimulator/commit/ab70591427688c68df2aac6b23fff062a57e7a0f#diff-fd978ef8ec81d7154b09d3c52bab9511
