### ISSUE TITLE
Projekt builden ohne Intellij

### ISSUE THREAD

**Issue by gutjuri** [PaulStahr/SimpleBoardGameSimulator#2]
Servus, wäre nice wenns eine Anleitung gäbe wie ich das Game builden kann. Optimalerweise mit Gradle o.Ä.

**Comment by bnw** [comment]
Fände ich auch gut. Hatte versucht eine Travis Pipeline einzurichten, bin aber gescheitert, weil ich nicht wusste, wie ich es von Kommandozeile aus kompilieren.
Kenne mich leider mit den Java build Tools nicht aus. Falls da niemand Expertise zu hat, würde es auch ein einfaches Makefile run.

**Comment by FMichaelis** [comment]
Ich hab angefangen mich mit Cradle auseinanderzusetzen, aber die buid-Datei ist noch ziemlich basic. Ich werde mich demnächst weiter dransetzen. Bin zumindest soweit gekommen, dass es anfängt zu builden und dann wegen der Dependencies failed :p

**Comment by FMichaelis** [comment]
An dieser Stelle ein Shoutout zu Ben (@bnw): Danke fürs fixen der Dependancies :D
